README
The description will need to be updated somewhat, but all of the components are here.
=> Added README.

R/clustering-functions.R, R/tsrFind.R
(Will connect to DGE analysis)
=> Added write functionality to tsrFind so that counts data can be retrieved.

R/tsrFind.R, R/tssExpr.R, demo/demo-CAGE.R, demo/demo-RAMPAGE.R, man/tssExpr.Rd
Also made slight updates to documentation for tssExpr and tsrFind.
=> Updated both demo files to reflect addition of tssExpr function.

R/bamToTSS.R
Also formatted bamToTSS in line with conventions (ie removing spaces)
=> bamToTSS now inserts list of appropriate length to the @expData slot. 

R/clustering-functions.R
This works for all my tests.  We should have test scaffolds with 0/1/multiple CTSSs on plus/minus only/both strands to test all cases.
The handling of "complete.cases()" is left for discussion.  The function only works properly for proper matrices (more than 1 row), when it eliminates rows with "NA" entries.  Do we ever need this?
=> fixed logic in clustering.functions.R

R/tsrToAnnotation.R, man/tsrToAnnotation.Rd
This update was principally tested on the Morton et al (2014) PEAT dataset from A. thaliana and also the human ENCODE CAGE dataset.
=> Updates to tsrToAnnotation, including an embedded check for the presence of an object in @geneAnnot prior to running.

R/mergeSampleData.R
=> Added message command to mergeSampleData

vignettes/TSRchitect.Rmd
This concerns handling the alignment files
=> Small addition to vignette

INSTALL.md, vignettes/TSRchitect.Rmd
As helpfully reported by Thomas.
=> Made minor corrections to Vignette 

INSTALL.md
In order to allow our automated code review to proceed successfully:
'master' is now 'devel' and 'Bioc' becomes 'master'. 
I will issue another pull request to close the loop, then we will remove the 'Bioc' branch (which will be 'master')
[Note that 'devel' is a new branch- this pull request doesn't delete any of our established codebase)]
=> Updated INSTALL file to reflect the new devel branch.

README.md
This will trigger the [push hook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) I added to this repo that will trigger an automatic build of the the package on TSRchitect.
=> Added departmental affiliation to README.md.

DESCRIPTION
See [this page](https://github.com/Bioconductor/Contributions/blob/13c78e10cadcaf3efaab4fbf89d8d70b83174bfd/CONTRIBUTING.md#adding-a-web-hook) for more information.
=> Renamed this build 0.99.1 as suggested by Bioconductor guidelines.

R/Show-methods.R, R/TSRchitectUsersGuide.R, R/addAnnotationToTSR.R, R/addTagCountsToTSR.R, R/bamToTSS.R, R/detTSR.R, R/mergeSampleData.R, R/prcTSS.R, R/tsr-metrics.R, R/tsrToDF.R, R/writeTSR.R, man/TSRchitectUsersGuide.Rd, man/addAnnotationToTSR.Rd, man/addTagCountsToTSR.Rd, man/bamToTSS.Rd, man/mergeSampleData.Rd, man/writeTSR.Rd, vignettes/TSRchitect.Rmd
The code passed the following tests on my R installation on gnomic:
`R CMD build TSRchitect`
`R CMD check TSRchitect_0.99.2.tar.gz`
`R CMD BiocCheck TSRchitect_0.99.2.tar.gz`
Please test on your end. 
If successful, I will then initiate moving these changes to the master branch."
=> Split up lines > 80 characters, and updated documentation as needed.

R/determineTSR.R, vignettes/TSRchitect.Rmd
Fixes error that was triggered when `parallel=TRUE` and `writeTable=TRUE`
=> Fixes to determineTSR

R/mergeSampleData.R
As requested. Also removed necessary loop from `determineTSR`.
=> Added refactored mergeSampleData

R/clustering-functions.R
Made a special focus on providing more information about the inputs (via `param`) and outputs (via `return`).
=> Added to documentation for the internal functions found in clustering-functions.R

DESCRIPTION
This will trigger a new automatic build on Bioconductor.
=> Updating version to 0.99.3

DESCRIPTION
- Changed R version (`Depends:`) to 3.4 from 3.3.0
- Updated version of package to 0.99.5
=> Updated R version in DESCRIPTION

R/inputToTSS.R
This enables SE BED file conversion.
=> Small update to inputToTSS() 

DESCRIPTION, INSTALL.md, NEWS, inst/CITATION
These minor changes make note of recent updates made to TSRchitect _e.g_. refer to its ability to handle EST/cDNA data.
=> Updates to DESCRIPTION, INSTALL and NEWS files; CITATION file added

DESCRIPTION, INSTALL.md, NEWS, inst/CITATION
These updates keep v 1.2.0 current and reflect its recent changes.
=> Merging updates from master into devel

DESCRIPTION, INSTALL.md, NEWS, inst/CITATION
- Minor updates of DESCRIPTION, INSTALL and NEWS files to better reflect recent updates to TSRchitect.
- Addition of new CITATION file for citation purposes.
=> Updated to version 1.2.1

DESCRIPTION, NEWS
A minor update describing version update to 1.2.1
=> Updated to 1.2.1

R/importAnnotationExternal.R, R/importAnnotationHub.R, inst/extdata/gsq_gff_extractor.pl, man/importAnnotationExternal-methods.Rd, man/importAnnotationHub-methods.Rd
which should now pass the build without warnings.
=> corrected links in documentation

Singularity, inst/doc/TSRchitectUsersGuide.Rmd
hopefully this takes care of getting the examples right
=> essential fixes to TSRchitectUsersGuide.Rmd, example 3

R/Get-methods.R, demo/HOWTO.md, demo/xdemo1, demo/xdemo2, demo/xdemo3, inst/doc/TSRchitectUsersGuide.Rmd
this version is better because otherwise the 'NA' of the actually empty file lists get printed
=> more accurate empty file list test

INSTALL.md
=> small typo

NEWS
- This had been requested by Lori Shepard from Bioconductor; I complied, but ignored the "+" characters. This has been corrected (and submitted)
=> Formatting update to NEWS section

INSTALL.md
- Replaced instance of biocLite() with BiocManager as per new BioC policy. ([https://cran.r-project.org/web/packages/BiocManager/vignettes/BiocManager.html](url))
- Reverted to most recent version of `INSTALL.md` (thus returning to the updates that were lost in the recent merger with the Bioc upstream branch)
=> Minor changes to INSTALL.md

Singularity
to include the needed XLConnect R package.
=> updated Singularity recipe

R/Show-methods.R
as shown in the changed lines of the file ...
=> fix of a logical error in Show-methods.R

README.md, Singularity.1.8.9
1) to reflect current R version in the container
2) to allow users to cite TSRchitect properly
3) to prepare a tagged singularity container
=> updated README.md; added Singularity.1.8.9 to tag this version

DESCRIPTION, NEWS, R/loadTSSobj.R, README.md
bumped version to 1.10 to match what seems to be required at Bioconductor
added qname for .bam input records
=> added qname to saved columns from .bam input

DESCRIPTION, NEWS, R/addAnnotationToTSR.R, vignettes/TSRchitect.Rmd
- to better summarize changes in current version (1.10.0) ahead of BioC update.
- this version is nearly identical (save for the removal of an extra Sing recipe) to that of the newly-created RELEASE_3_9 branch, which I will send a pull request for momentarily.
=> Updated NEWS

R/detTSR.R
in detTSR.R (minor, but significant!)
=> minor error correction

DESCRIPTION, NEWS, R/detTSR.R, README.md
- TSRchitect version number updated to 1.12.2
- updates to `DESCRIPTION`, `NEWS` and `README.md` to reflect the new version number
- this update incorporates the recent bug fix in `detTSR()` (made by @vpbrendel) in branch master
=> Creation of RELEASE_3_10 branch

DESCRIPTION, NEWS, README.md
- to harmonize with version 1.11.12 on the master (for Bioc, the devel) branch
=> Updated to version 1.10.12

R/Show-methods.R
... just while I noticed this; of minor significance
=> minor message correction

DESCRIPTION, NEWS, README.md
- changes to DESCRIPTION`, `NEWS`, and `README.md` to reflect version update
- mentioned new feature introduced by changes to `writeTSS()` by @vpbrendel in previous commit.
=> Update to version 1.13.4

R/loadTSSobj.R, Singularity
1) loadTSSobj.R fix was not correctly submitted. Now fixed.
2) There were problems with recreating our Singularity container due to changes in system/ancillary programs. The current submission should work.
=> fixes typo in loadTSSobj.R and adjusts Singularity

DESCRIPTION, NEWS, README.md
- syncing our repo with Bioc after their move to version 3.11 last month.
- the TSRchitect release version was updated to 1.14.1
- updated `DESCRIPTION`, `NEWS` and `README.md` to reflect the above
=> Updating version in new branch after update to RELEASE_3_11

DESCRIPTION, NEWS, README.md
Merged with upstream branch and updated the following files to reflect the version changes
- DESCRIPTION
- README.md
- NEWS
=> Minor updates to reflect version bump upon Bioc 3.12 release
