R/Allclasses.R
R/Show-methods.R
R/bamToTSS.R
R/clustering-functions.R
R/importBam.R
R/initializeExp.R
R/tsrFind.R
R/tssExpr.R

I added consistent handling of reporting messages:
message() like stop() goes to stderr, whereas cat() goes to stdout.  We should have progress notes on stderr, but record keeping in stdout.  Now we can run TSRchitect commands with Rscript from a file x as follows:
Rscript --default-packages=methods,utils,stats x > output
which will show progress on stderr, while keeping other messages in file output.
I also made some changes for consistency, most importantly using expName as second argument for initializeExp, as we do in all other places.  Output files for tsrFind are properly names TSRset-x.txt, to go along with CTSSset-x.txt from tssExpr.R.

many updates to workflow progress reporting, general code syntax

---

R/clustering-functions.R

This fix in .tsrCluster addresses a couple of serious bugs in the code that resulted in wrong output:
1) The final TSR was not reported in the previous code when the last tss was to be merged.
2) Current lines 216 and 222 were missed/incorrect, respectively, presumably as a result of faulty copy/paste from the plus strand handling code.  This resulted in wrong TSR reporting on the minus strand.
As always, the new code should be thoroughly vetted against example data checked "by hand".

fixes for serious bugs in clustering-functions.R

---

R/bamToTSS.R
R/importBam.R

Corrects an off-by-one handling issue for TSSs on the negative strand.

Update bamToTSS identify TSSs as only a single coordinate in the GRanges object. 

---

R/clustering-functions.R

The error disrupted control flow for scaffolds with few mapped TSSs. Simple fix.

Corrected error in expressionCTSS() 

---

R/Get-methods.R
man/getTSRdata.Rd
vignettes/TSRchitect.Rmd

Also, corrected an error in one of the examples in the documentation.

Updated the vignette to include an accessor method example. 

---

R/addAnnotationToTSR.R
R/addTagCountsToTSR.R
R/bamToTSS.R
R/determineTSR.R
R/importAnnotationHub.R
R/mergeSampleData.R
R/processTSS.R
R/setSampleID.R
man/addAnnotationToTSR.Rd
man/addTagCountsToTSR.Rd
man/bamToTSS.Rd
man/determineTSR.Rd
man/importAnnotationHub.Rd
man/mergeSampleData.Rd
man/processTSS.Rd
man/setSampleID.Rd

1. Removed specific references to Example 1 in vignette, which had been removed. 
2. fileNames length requirement in `setSampleID` as discussed. 
3. Split up long >80 character lines in `determineTSR`.

Update to setSampleID; other various minor updates

---

R/determineTSR.R

This error was caught using `R CMD check` and was not encountered by any of the demos, etc.

Made small correction in determineTSR.

---

R/addAnnotationToTSR.R
R/addTagCountsToTSR.R
R/bamToTSS.R
R/clustering-functions.R
R/determineTSR.R
R/importAnnotationExternal.R
R/importAnnotationHub.R
R/importBam.R
R/initializeExp.R
R/mergeSampleData.R
R/processTSS.R
R/setSampleID.R

This code update is the first implementation with "return" instead of "assign to parent frame".
Checked on the the demo AtPEAT example; see updated AtPEAT.Rscript.
Other demo examples have not been updated.
To do: initializeExp should be combined with importBam and setSampleID; see methRead in methylKit for an example.  The function could be "setupTSR" and be invoked as
AtPEAT <- setupTSR( arguments )
where arguments are the the relevant arguments from importBam and setSampleID.

updates the get rid of assign to parent frame

---

R/addAnnotationToTSR.R
R/addTagCountsToTSR.R
R/tsrToDF.R
R/writeTSR.R
vignettes/TSRchitect.Rmd

Loops in `tsrToDF()` was refactored using `lapply`, `vapply`, `sapply` and `do.call(rbind, ...)` as requested by BioC review.
References to deprecated code in the vignette were removed.

Corrections to vignette and tsrToDF()

---

R/addAnnotationToTSR.R

Hard-coded `$ID` argument within function prevented assignment of annotation to TSRs. if original file was in BED format (as opposed to GFF3).
Note: This build passed both the i) HsCAGE and ii) AtPEAT demos.

Corrected error in addAnnotationToTSR() 

---

R/createSummarizedExperiment.R
man/createSummarizedExperiment.Rd

Typo prevented example from running correctly. Thanks @vpbrendel for the catch.

Corrected typo in documentation of createSummarizedExperiment()

---

R/Show-methods.R

These prevent warnings from being triggered when object is returned on the console.

Minor changes to Show Methods 

---

R/loadTSSobj.R

This had prevented import when a single .bed file was to be imported.

Corrected issue in loadTSSobj() 

---

R/Get-methods.R

Example 1 in our TSRchitectUsersGuide showed that exists() does not work as we had it.

fix for incorrect implementation of getFileNames()

---

R/clustering-functions.R
R/determineTSR.R
R/processTSS.R

- parallelization over sequences was found to be costing more in overhead than there are gains
- the correct implementation of growing the TSS matrix provides the crucial time savings
- register is now used to correctly change biocParallel parameters
- some minor clean-up of variable naming and indentation
This should be ready for thorough independent testing.

completed reworking for bplapply

---

DESCRIPTION
INSTALL.md
NEWS
inst/doc/TSRchitectUsersGuide.Rmd

- also reverted `TSRchitect` version to 1.8.9 to reflect BioC policies on version numbering [https://bioconductor.org/developers/how-to/version-numbering/](url) 
- replaced instances of `biocLite()` with `BiocManager()` as per (recently adopted) Bioconductor policy ([https://cran.r-project.org/web/packages/BiocManager/vignettes/BiocManager.html](url))
- all recent updates should now be ready for submission to Bioconductor github branch

Updated NEWS to reflect latest changes

---

R/writeTSR.R
man/writeTSR-methods.Rd

This update addresses several issues:
1) The current function still uses the shapeIndex variable which has long been deprecated, resulting in an error when trying to write bed output.
2) The pull request addresses Issue #171 which made a very reasonable suggestion to provide output in forms that can be uploaded by modern genome browsers. The re-write allows .bed or .gff output; these files could be directly uploaded as tracks to USCF Browser or JBrowse, respectively. Tested for Arabidopsis.
3) The issue also suggested to score TSRs.  This is done in this re-write by re-scaling the nTAGs variable of a TSR to a value between 0 and 1000, as requested, using the exponential distribution properties of the variable.
The updates should be properly tested independently ... (as always).
Volker

writeTSR revamped

---

DESCRIPTION
NEWS
README.md

- After sync with Bioconductor repo in preparation for submission of recent updates, learned that version needs to be changed to 1.12.0 because of automatic version bumps by BioC.
- Updated references to version in DESCRIPTION, NEWS, and README.md.
- Once merged I will submit to this branch to the Bioconductor git repo.

Updated references to version 1.12.0 as required by Bioconductor.

---

DESCRIPTION
NEWS
README.md

- According to the versioning system x.y.z, only z can be changed by the maintainer/developer. 
- The branch master should be thought of as the devel, and y needs to be 1 number ahead of the current release (currently RELEASE_3_9).
- Updates with a change to z in the description will trigger a new bioconductor build
- y will be changed by Bioconductor at the point of every release: 2x per year.
Please see [http://bioconductor.org/developers/how-to/version-numbering/](here) for further reference.

Corrected version to 1.11.11 to reflect BioC's version requirements

---

DESCRIPTION
NEWS
README.md

- According to the versioning system x.y.z, only z can be changed by the maintainer/developer. 
- Updates to the current release with a change to z in the description will trigger a new bioconductor build.
- y will be changed by Bioconductor at the point of every release: 2x per year.
Please see [http://bioconductor.org/developers/how-to/version-numbering/](here) for further reference.

Corrected version to 1.10.10 in accordance with BioC policies.

---

DESCRIPTION
NEWS
R/loadTSSobj.R
README.md

- Recently on the devel branch of Bioconductor (Bioc 3.11), there were changes made to the automatic build that trigger build errors in certain instances. This change meant that logicals in `loadTSSobj()` was triggering  build errors.
- I changed this and updated the version of TSRhitect to '1.13.5' to reflect this change.

Corrected logicals in loadTSSobj.R that were triggering a build error.

---

DESCRIPTION
NEWS
README.md

- syncing our master with Bioc's devel branch after their move to version 3.11 (3.12 for devel) last month.
- the TSRchitect release version was updated to 1.15.1
- updated `DESCRIPTION`, `NEWS` and `README.md` to reflect the above

Updating master (i.e. the Bioc devel branch) due to release of BioC 3.11
